# -*- coding: utf-8 -*-
"""estudos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bLvIId0DXsqP33NmMn-ATEwdcCJ5wkjB

# Começando em Python.
"""

print("Hello")

num1 = int(input("Digite um numero: "))
num2 = int(input("Digite outro numero: "))
soma = num1 + num2
print(f"A soma dos dois é: {soma}")

"""# Tipos de variáveis:

*   Inteiro(INT): números inteiros.
*   Float: números de ponto flutuante. Com casas decimais.
*   Decimal: maior precisão do que um Float.
*   Alfanumérico (String): Armazenar textos em geral.
NO PYTHON NÃO PRECISAMOS DECLARAR OS TIPOS DE VARIÁVEIS!!!


"""

numero_filhos = 4
numero_filhos

type(numero_filhos)

preco_produto = 3.55
preco_produto

print(preco_produto*10)

type(preco_produto)

"""Variáveis Textuais"""

nome = "Fernando"
print("Bem vindo " + nome)

type(nome)

novo_nome = input("Digite seu nome: ")
print("Seja bem vindo(a) " + novo_nome)

"""# Funções


*   Bolocos de código que podem ser executados diversas vezes
*   Podem ou não receber dados ( chamados de parâmetros)

*   Podem retornar algum valor após sua operação
*   Usamos Funções nativas e de terceiros no Python

---
Anatomia de uma função:

    def nomedafunção (parâmetros opcionais)
        código indentado1
        mais código indentado...
        return algum valor







"""


def multiplicar_numeros(num1, num2):
    resultado = num1 * num2
    return resultado


multiplicar_numeros(2, 4)

"""# Documentar a Função:

*   Inserir os parâmetros dentro de 3 aspas duplas


"""


def multiplicar_numeros(num1, num2):
    """
      Função para multiplicar números

    Parâmetros
      num1: int
        primeiro número
      num2: int
        segundo número

    Retorna
      int
        Resultado multiplicação
    """
    resultado = num1 * num2
    return resultado


multiplicar_numeros(8, 8)

# Calculo IMC


def calcular_imc(peso, altura):
    imc = peso / (altura * altura)
    peso = int(input("Digite seu peso: "))
    altura = float(input("Digite sua altura: "))
    if (imc < 18.5):
        print("Abaixo do peso")
    else:
        if (imc < 24.9):
            print("Peso normal")
        elif (imc >= 30):
            print("Obesidade")
        else:
            print(imc)
            print("Sobrepeso")
    return imc


calcular_imc(82, 1.76)
calcular_imc(70, 1.70)
